# Generated by Django 3.2.25 on 2025-02-13 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0002_testorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('specialization', models.CharField(choices=[('Pediatrics', 'Pediatrics'), ('Surgery', 'Surgery'), ('Psychiatry', 'Psychiatry'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology'), ('Radiology', 'Radiology'), ('Anesthesiology', 'Anesthesiology'), ('Oncology', 'Oncology'), ('Gynecology', 'Gynecology'), ('Urology', 'Urology'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('Pulmonology', 'Pulmonology'), ('Nephrology', 'Nephrology'), ('Ophthalmology', 'Ophthalmology'), ('Otolaryngology', 'Otolaryngology'), ('Emergency Medicine', 'Emergency Medicine'), ('Family Medicine', 'Family Medicine')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
